import subprocess, zipfile, shutil, os, re, io
out=subprocess.run(["pandoc","--print-default-data-file=reference.docx"],capture_output=True)
open("/tmp/reference.docx","wb").write(out.stdout)
shutil.rmtree("/tmp/refx", ignore_errors=True); os.makedirs("/tmp/refx")
with zipfile.ZipFile("/tmp/reference.docx") as z: z.extractall("/tmp/refx")
p="/tmp/refx/word/styles.xml"; s=io.open(p,encoding="utf-8").read()
s=re.sub(r'<w:rFonts[^/]*/>','<w:rFonts w:ascii="Malgun Gothic" w:hAnsi="Malgun Gothic" w:eastAsia="Malgun Gothic" w:cs="Malgun Gothic"/>',s)
s=re.sub(r'<w:sz w:val="\d+"\s*/>','<w:sz w:val="20"/>',s)
s=re.sub(r'<w:szCs w:val="\d+"\s*/>','<w:szCs w:val="20"/>',s)
s=re.sub(r'<w:spacing w:before="\d+"','<w:spacing w:before="80"',s)
s=re.sub(r'w:after="\d+"','w:after="40"',s)
s=re.sub(r'w:line="\d+" w:lineRule="[a-z]+"','w:line="240" w:lineRule="auto"',s)
io.open(p,"w",encoding="utf-8").write(s)
p2="/tmp/refx/word/document.xml"; s2=io.open(p2,encoding="utf-8").read()
s2=re.sub(r'<w:pgMar[^/]*/>','<w:pgMar w:top="1021" w:right="1021" w:bottom="1021" w:left="1021" w:header="567" w:footer="567" w:gutter="0"/>',s2)
io.open(p2,"w",encoding="utf-8").write(s2)
if os.path.exists("/tmp/reference2.docx"): os.remove("/tmp/reference2.docx")
subprocess.run(["zip","-Xrq","/tmp/reference2.docx","."],cwd="/tmp/refx",check=True)
print("reference2 생성")
